// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2YrNzlWbekXiEkjz2eBu8CvRmzxUGkw',
    appId: '1:843553972017:web:bb0dee881e72f362ef9a10',
    messagingSenderId: '843553972017',
    projectId: 'apptripsric',
    authDomain: 'apptripsric.firebaseapp.com',
    storageBucket: 'apptripsric.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUoS7DA21IOytTKF9oGVOlQqMQSZyoVM',
    appId: '1:843553972017:android:68a97fdc9a815a01ef9a10',
    messagingSenderId: '843553972017',
    projectId: 'apptripsric',
    storageBucket: 'apptripsric.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3PdG2EnAsvqGbrJQajC20nvGIeJGEUp8',
    appId: '1:843553972017:ios:56d442b3e9c1b53def9a10',
    messagingSenderId: '843553972017',
    projectId: 'apptripsric',
    storageBucket: 'apptripsric.appspot.com',
    iosClientId: '843553972017-9edi7rkkc48ai2n4rp9uudsq6qtc4m0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripsApp',
  );
}
